[package]
name = "zellij_forgot"
version = "0.1.0"
edition = "2021"
authors = ["Karim Ould Mahieddine"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
owo-colors = "3.5.0"
zellij-tile = "0.38.0"
chrono = "0.4.0"
